INSERT INTO "completedPaymentRequests"(
  "paymentRequestId",
  "schemeId",
  ledger,
  "sourceSystem",
  "deliveryBody",
  "invoiceNumber",
  frn,
  sbi,
  "agreementNumber",
  "contractNumber",
  currency,
  schedule,
  "dueDate",
  value,
  acknowledged,
  "marketingYear",
  "debtType",
  "recoveryDate",
  "originalSettlementDate",
  "originalInvoiceNumber",
  "invoiceCorrectionReference",
  submitted,
  "paymentRequestNumber",
  invalid,
  "settledValue",
  "lastSettlement",
  "referenceId",
  "correlationId",
  batch,
  "paymentType",
  pillar,
  "exchangeRate",
  "eventDate",
  vendor,
  trader,
  "claimDate",
  migrated,
  "migrationId")
SELECT
  "paymentRequests"."paymentRequestId",
  "tempCompletedPaymentRequests"."schemeId",
  "tempCompletedPaymentRequests".ledger,
  "tempCompletedPaymentRequests"."sourceSystem",
  "tempCompletedPaymentRequests"."deliveryBody",
  "tempCompletedPaymentRequests"."invoiceNumber",
  "tempCompletedPaymentRequests".frn,
  "tempCompletedPaymentRequests".sbi,
  "tempCompletedPaymentRequests"."agreementNumber",
  "tempCompletedPaymentRequests"."contractNumber",
  "tempCompletedPaymentRequests".currency,
  "tempCompletedPaymentRequests".schedule,
  "tempCompletedPaymentRequests"."dueDate",
  "tempCompletedPaymentRequests".value,
  "tempCompletedPaymentRequests".acknowledged,
  "tempCompletedPaymentRequests"."marketingYear",
  "tempCompletedPaymentRequests"."debtType",
  TO_CHAR("tempCompletedPaymentRequests"."recoveryDate",
  'DD/MM/YYYY') AS "recoveryDate",
  TO_CHAR("tempCompletedPaymentRequests"."originalSettlementDate",
  'DD/MM/YYYY') AS "originalSettlementDate",
  "tempCompletedPaymentRequests"."originalInvoiceNumber",
  "tempCompletedPaymentRequests"."invoiceCorrectionReference",
  "tempCompletedPaymentRequests".submitted,
  "tempCompletedPaymentRequests"."paymentRequestNumber",
  "tempCompletedPaymentRequests".invalid,
  "tempCompletedPaymentRequests"."settledValue",
  "tempCompletedPaymentRequests"."lastSettlement",
  "tempCompletedPaymentRequests"."referenceId",
  "tempCompletedPaymentRequests"."correlationId",
  "tempCompletedPaymentRequests".batch,
  "tempCompletedPaymentRequests"."paymentType",
  "tempCompletedPaymentRequests".pillar,
  "tempCompletedPaymentRequests"."exchangeRate",
  "tempCompletedPaymentRequests"."eventDate",
  "tempCompletedPaymentRequests".vendor,
  "tempCompletedPaymentRequests".trader,
  "tempCompletedPaymentRequests"."claimDate",
  "paymentRequests".migrated,
  "paymentRequests"."migrationId"
FROM "tempCompletedPaymentRequests"
LEFT JOIN "completedPaymentRequests"
  ON "tempCompletedPaymentRequests"."migrationId" = "completedPaymentRequests"."migrationId"
INNER JOIN "paymentRequests"
  ON "tempCompletedPaymentRequests"."migrationId" = "paymentRequests"."migrationId"
WHERE "completedPaymentRequests"."migrationId" IS NULL
  AND "tempCompletedPaymentRequests" != 7;